/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, View} from 'react-native';
import AdyenExample from './AdyenExample';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
  };

  render() {
    return (
      <View style={styles.container}>
        <AdyenExample />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
